### ISSUE TITLE
Position of Popover is wrong, its fixed to top left

### ISSUE THREAD

**Issue by Venipa** [floating-ui/react-popper#432]
### Reproduction demo

[Codesandbox Demo](https://codesandbox.io/s/tailwind-react-headlessui-popper-5c15b?file=/src/components/Homepage.js)

### Steps to reproduce the problem

1.  Click Red Field
2.  Wrong position

### What is the expected behavior?

That the popover renders to the right start of the ref element.

### What went wrong?

Popover position is set to top 0px, left 0px

### Any other comments?

-

### Packages versions

- Popper.js: @popperjs/core@2.11.0
- react-popper: 2.2.5

**Comment by mschaeffner-orca** [comment]
I have the same issue. My current workaround is to use `@popperjs/core@2.10.2`.

**Comment by Venipa** [comment]
https://github.com/tailwindlabs/headlessui/issues/985
