### ISSUE TITLE
Feature: Close on click outside Boolean property

### ISSUE THREAD

**Issue by hichemfantar** [floating-ui/react-popper#449]
A property to specify whether the dropdown should close on click outside or not would be very useful.

**Comment by viktoryoo** [comment]
Agree. It took me some time to implement a custom hook to inspect a mouse event when is clicked outside of the poper to close it...

**Comment by atomiks** [comment]
`react-popper` (and `@floating-ui/react-dom)` only handles positioning

Use [Floating UI Interactions](https://floating-ui.com/docs/react-dom-interactions) to handle all types of interactions, including outside clicks
